// @ts-check

// Sidebar situs panduan (`/docs/*`). DUA sidebar, bukan sepuluh: `panduanSidebar`
// untuk halaman pengantar, dan `fiturSidebar` untuk seluruh isi `docs/fitur/`.
// Diketok user 10 September 2026, menggantikan susunan satu-sidebar-per-fitur
// yang berlaku 9 September 2026. Alasannya di ADR-0021.
//
// Docusaurus memilih sidebar berdasarkan sidebar mana yang memuat dokumen
// aktif, jadi tiap dokumen wajib muncul di tepat satu sidebar di bawah ini.
// Dokumen yang tidak terdaftar hanya memicu PERINGATAN saat build, bukan galat
// — halamannya terbit tanpa navigasi apa pun.
//
// Menambah fitur berarti tiga langkah: folder baru di `docs/fitur/`, satu entri
// di `fiturSidebar`, dan satu butir di menu Fitur pada `docusaurus.config.js`.
// Halaman ringkasnya di `docs/fitur-aplikasi/` menyusul sebagai langkah
// keempat bila fitur itu perlu muncul di Panduan.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Lima butir Panduan, urut seperti daftar user 10 September 2026. Ditulis
  // eksplisit, bukan `autogenerated`: `autogenerated` di akar `docs/` akan
  // menyapu `docs/fitur/` ikut masuk ke sidebar ini.
  panduanSidebar: [
    'intro',
    'glosarium',
    {
      type: 'category',
      label: '🌐 Sumber Data',
      // Halaman induknya tetap punya isi sendiri — cakupan, kunci join, dan
      // catatan mutu — jadi kategorinya menaut ke dokumen itu, bukan ke
      // indeks bangkitan.
      link: {type: 'doc', id: 'sumber-data/index'},
      items: ['sumber-data/pipeline-utama', 'sumber-data/tambahan'],
    },
    'peran-pengguna',
    {
      // TANPA `link`: kategori ini tidak punya halaman sendiri, jadi
      // mengekliknya hanya membuka kedua subkelompoknya.
      type: 'category',
      label: '📌 Fitur di Aplikasi',
      items: [
        {
          type: 'category',
          label: 'Fitur Utama',
          items: [
            'fitur-aplikasi/utama/peta-peran',
            'fitur-aplikasi/utama/kartu-ekonomi-desa',
            'fitur-aplikasi/utama/jalur-ekonomi',
            'fitur-aplikasi/utama/desa-kembar',
            'fitur-aplikasi/utama/citra-potensi-desa',
          ],
        },
        {
          type: 'category',
          label: 'Fitur Tambahan',
          items: [
            'fitur-aplikasi/tambahan/asisten-desa',
            'fitur-aplikasi/tambahan/berita-desa',
            'fitur-aplikasi/tambahan/laporan-desa',
            'fitur-aplikasi/tambahan/halaman-admin',
          ],
        },
      ],
    },
  ],

  // Seluruh fitur di satu pohon. Lima fitur utama masing-masing kategori
  // `autogenerated` supaya halaman baru di dalamnya cukup diberi
  // `sidebar_position` tanpa menyentuh berkas ini. Empat fitur tambahan masih
  // satu halaman masing-masing, jadi ditulis sebagai dokumen langsung.
  fiturSidebar: [
    'fitur/index',
    {
      type: 'category',
      label: 'Fitur Utama',
      items: [
        {
          type: 'category',
          label: 'Peta Peran',
          items: [{type: 'autogenerated', dirName: 'fitur/peta-peran'}],
        },
        {
          type: 'category',
          label: 'Kartu Ekonomi Desa',
          items: [{type: 'autogenerated', dirName: 'fitur/kartu-ekonomi-desa'}],
        },
        {
          type: 'category',
          label: 'Jalur Ekonomi',
          items: [{type: 'autogenerated', dirName: 'fitur/jalur-ekonomi'}],
        },
        {
          type: 'category',
          label: 'Desa Kembar',
          items: [{type: 'autogenerated', dirName: 'fitur/desa-kembar'}],
        },
        {
          type: 'category',
          label: 'Citra Potensi Desa',
          items: [{type: 'autogenerated', dirName: 'fitur/citra-potensi-desa'}],
        },
      ],
    },
    {
      type: 'category',
      label: 'Fitur Tambahan',
      items: [
        'fitur/asisten-desa/pengenalan',
        'fitur/berita-desa/pengenalan',
        'fitur/laporan-desa/pengenalan',
        'fitur/halaman-admin/pengenalan',
      ],
    },
  ],
};

export default sidebars;
