// @ts-check

// Sidebar situs panduan (`/docs/*`). DUA sidebar, bukan sepuluh: `panduanSidebar`
// untuk halaman pengantar, dan `fiturSidebar` untuk seluruh isi `docs/fitur/`.
// Diketok user 10 September 2026, menggantikan susunan satu-sidebar-per-fitur
// yang berlaku 9 September 2026. Alasannya di ADR-0021.
//
// Docusaurus memilih sidebar berdasarkan sidebar mana yang memuat dokumen
// aktif, jadi tiap dokumen wajib muncul di tepat satu sidebar di bawah ini.
// Dokumen yang tidak terdaftar hanya memicu PERINGATAN saat build, bukan galat
// — halamannya terbit tanpa navigasi apa pun.
//
// Menambah fitur berarti tiga langkah: folder baru di `docs/fitur/`, satu entri
// di `fiturSidebar`, dan satu butir di menu Fitur pada `docusaurus.config.js`.
// Halaman ringkasnya di `docs/fitur-aplikasi/` menyusul sebagai langkah
// keempat bila fitur itu perlu muncul di Panduan.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Lima butir Panduan, urut seperti daftar user 10 September 2026. Ditulis
  // eksplisit, bukan `autogenerated`: `autogenerated` di akar `docs/` akan
  // menyapu `docs/fitur/` ikut masuk ke sidebar ini.
  panduanSidebar: [
    'intro',
    'glosarium',
    {
      type: 'category',
      label: '📊 Data',
      items: [
        {
          type: 'category',
          label: '🌐 Sumber Data',
          link: {type: 'doc', id: 'sumber-data/index'},
          items: ['sumber-data/pipeline-utama', 'sumber-data/tambahan'],
        },
        {
          type: 'category',
          label: '⚙️ Pengolahan Data',
          link: {type: 'doc', id: 'pengolahan-data/index'},
          items: [
            'pengolahan-data/peta-peran',
            'pengolahan-data/kartu-ekonomi-desa',
            {
              type: 'doc',
              id: 'pengolahan-data/citra-potensi-desa',
              label: 'Citra Potensi Desa',
              className: 'sidebar-badge-ml',
            },
            {
              type: 'doc',
              id: 'pengolahan-data/desa-kembar',
              label: 'Desa Kembar',
              className: 'sidebar-badge-ml',
            },
            {
              type: 'doc',
              id: 'pengolahan-data/jalur-ekonomi',
              label: 'Jalur Ekonomi',
              className: 'sidebar-badge-ml',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '👥 Pengguna',
      items: ['peran-pengguna', 'akun-demo'],
    },
    {
      // TANPA `link`: kategori ini tidak punya halaman sendiri, jadi
      // mengekliknya hanya membuka kedua subkelompoknya.
      type: 'category',
      label: '📌 Fitur pada Aplikasi',
      items: [
        {
          type: 'category',
          label: 'Fitur Utama',
          items: [
            'fitur-aplikasi/utama/peta-peran',
            'fitur-aplikasi/utama/kartu-ekonomi-desa',
            'fitur-aplikasi/utama/jalur-ekonomi',
            'fitur-aplikasi/utama/desa-kembar',
            'fitur-aplikasi/utama/citra-potensi-desa',
          ],
        },
        {
          type: 'category',
          label: 'Fitur Tambahan',
          items: [
            'fitur-aplikasi/tambahan/asisten-desa',
            'fitur-aplikasi/tambahan/ai-insight',
            'fitur-aplikasi/tambahan/berita-desa',
            'fitur-aplikasi/tambahan/laporan-desa',
            'fitur-aplikasi/tambahan/halaman-admin',
          ],
        },
      ],
    },
    'pengembangan-lebih-lanjut',
  ],

  // Seluruh fitur di satu pohon. Lima fitur utama masing-masing kategori
  // `autogenerated` supaya halaman baru di dalamnya cukup diberi
  // `sidebar_position` tanpa menyentuh berkas ini. Lima fitur tambahan masih
  // satu halaman masing-masing, jadi ditulis sebagai dokumen langsung.
  fiturSidebar: [
    'fitur/index',
    {
      type: 'category',
      label: 'Fitur Utama',
      items: [
        'fitur/peta-peran/pengenalan',
        'fitur/kartu-ekonomi-desa/pengenalan',
        'fitur/jalur-ekonomi/pengenalan',
        'fitur/desa-kembar/pengenalan',
        'fitur/citra-potensi-desa/pengenalan',
      ],
    },
    {
      type: 'category',
      label: 'Fitur Tambahan',
      items: [
        'fitur/asisten-desa/pengenalan',
        'fitur/ai-insight/pengenalan',
        'fitur/berita-desa/pengenalan',
        'fitur/laporan-desa/pengenalan',
        'fitur/halaman-admin/pengenalan',
      ],
    },
  ],
};

export default sidebars;
