// @ts-check

// Sidebar situs rujukan REST APIs (`/api/*`).
//
// BUKAN `autogenerated`: susunannya adalah halaman pengantar buatan tangan di
// atas, lalu potongan sidebar hasil bangkitan
// `docusaurus-plugin-openapi-docs`. Potongan itu keluaran — urutan kategori
// dan labelnya berasal dari `openapi_tags` di `../api/src/main.py`, bukan dari
// berkas ini. Bangkitkan ulang dengan `npm run api:bangkit`.

import sidebarOpenapi from './docs-api/endpoint/sidebar.ts';

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  apiSidebar: ['intro', ...sidebarOpenapi],
};

export default sidebars;
